### ISSUE TITLE
undefined method 'content'

### ISSUE THREAD

**Issue by ghost** [grosser/smusher#6] opened 2011-04-21 18:36 UTC
I'm getting an error on every image:

<pre>smushing header.png
undefined method `content' for #<String:0x10189bd48>
47929 -> 47929                           = 100%</pre>

Any ideas?  (I made sure to get my own API key.)

**Comment by grosser** [comment] 2011-04-21 19:16
1.9 bug I think ,someone else already had a similar error, ill try to fix that, use 1.8.7 for now (e.g. `alias smusher="rvm 1.8.7 exec smusher"`)

**Comment by ghost** [comment] 2011-04-21 19:55
It should be on ruby 1.8.7 already.

<pre>$ ruby -v
ruby 1.8.7 (2009-06-12 patchlevel 174) [universal-darwin10.0]</pre>


I installed rvm, but I'm having trouble getting smusher to run within it.  (I'm an rvm n00b):

<pre>$ gem which smusher
/Library/Ruby/Gems/1.8/gems/smusher-0.4.7/lib/smusher.rb

$ rvm 1.8.7 exec smusher
/Library/Ruby/Site/1.8/rubygems.rb:926:in `report_activate_error': Could not find RubyGem smusher (>= 0) (Gem::LoadError)
    from /Library/Ruby/Site/1.8/rubygems.rb:244:in `activate_dep'
    from /Library/Ruby/Site/1.8/rubygems.rb:236:in `activate'
    from /Library/Ruby/Site/1.8/rubygems.rb:1307:in `gem'
    from /usr/bin/smusher:18

$ rvm 1.8.7 gem install smusher
WARN: 'gem not found for ruby-1.8.7-p334' either does not exist or is not executable? :(</pre>


Let me know what other info might be helpful. Thanks for your time!

**Comment by grosser** [comment] 2011-04-21 20:07
nope, unable to reproduce this, which ruby version are you using / which command are you using to smush the image ?

**Comment by ghost** [comment] 2011-04-21 20:22
ruby 1.8.7 (2009-06-12 patchlevel 174) [universal-darwin10.0]

I'm making progress with rvm.  Hopefully 1.8.7-p334 will make smusher happy.

**Comment by ghost** [comment] 2011-04-21 21:19
No luck.  I got patch334 installed, but I still have the same issue. Let me know if there are any informational calls I can give that might provide more insight :(

<pre>$ ruby -v
ruby 1.8.7 (2011-02-18 patchlevel 334) [i686-darwin10.7.0]

$ smusher Arrow.png 
smushing Arrow.png
undefined method `content' for #&lt;String:0x1011725d0&gt;
801 -> 801                               = 100%

$ rvm 1.8.7 exec smusher Arrow.png 
smushing Arrow.png
undefined method `content' for #&lt;String:0x1011725d0&gt;
801 -> 801                               = 100%

$ rvm 1.8.7 exec smusher --service PunyPng Arrow.png 
smushing Arrow.png
undefined method `content' for #&lt;String:0x101171f68&gt;
801 -> 801                               = 100%</pre>

**Comment by grosser** [comment] 2011-04-22 08:22
new http-client version worked slightly different, is fixed now :)

**Closed as completed by grosser** 2011-04-22 08:22 UTC

**Comment by ghost** [comment] 2011-04-22 14:35
Thanks!
